import type { Field, Resource, ResourceConfig } from './types';
const all = ['owner', 'moderator', 'support', 'editor'] as const;
const column = (key: string, label: string, type?: 'status' | 'date' | 'money') => ({
  key,
  label,
  type,
});
const f = (
  key: string,
  label: string,
  type: Field['type'] = 'text',
  required = false,
  options?: string[],
): Field => ({ key, label, type, required, options });
export const resources: Record<Resource, ResourceConfig> = {
  users: {
    title: 'Utilisateurs',
    singular: 'Utilisateur',
    description: 'Retrouvez un compte et suivez son activité sur LocaMap.',
    roles: ['owner', 'moderator', 'support'],
    group: 'operations',
    statuses: ['ACTIVE', 'SUSPENDED', 'HOST', 'TENANT', 'PENDING', 'VERIFIED'],
    columns: [
      column('full_name', 'Utilisateur'),
      column('email', 'Email'),
      column('kyc_status', 'Identité', 'status'),
      column('created_at', 'Inscription', 'date'),
    ],
  },
  hosts: {
    title: 'Validations hôtes',
    singular: 'Dossier hôte',
    description: 'Examinez les justificatifs et prenez une décision motivée.',
    roles: ['owner', 'moderator'],
    group: 'operations',
    statuses: ['PENDING', 'APPROVED', 'REJECTED'],
    columns: [
      column('legal_name', 'Nom déclaré'),
      column('status', 'État', 'status'),
      column('submitted_at', 'Soumis le', 'date'),
      column('reviewed_at', 'Examiné le', 'date'),
    ],
  },
  properties: {
    title: 'Annonces',
    singular: 'Annonce',
    description: 'Vérifiez les logements avant leur publication.',
    roles: ['owner', 'moderator', 'support'],
    group: 'operations',
    statuses: ['PENDING_REVIEW', 'ACTIVE', 'DRAFT', 'SUSPENDED', 'ARCHIVED'],
    columns: [
      column('title', 'Logement'),
      column('city', 'Ville'),
      column('price_per_month', 'Loyer / mois', 'money'),
      column('status', 'État', 'status'),
    ],
  },
  bookings: {
    title: 'Réservations',
    singular: 'Réservation',
    description: 'Suivez les demandes et les séjours. Aucun paiement n’est encaissé dans LocaMap.',
    roles: ['owner', 'support', 'moderator'],
    group: 'operations',
    statuses: ['pending', 'approved', 'rejected', 'cancelled', 'completed'],
    columns: [
      column('property_title', 'Logement'),
      column('start_date', 'Arrivée', 'date'),
      column('end_date', 'Départ', 'date'),
      column('total_price', 'Montant prévu', 'money'),
      column('status', 'État', 'status'),
    ],
  },
  tickets: {
    title: 'Assistance',
    singular: 'Demande d’assistance',
    description: 'Répondez aux utilisateurs et accompagnez la résolution de leurs demandes.',
    roles: ['owner', 'support'],
    group: 'operations',
    statuses: ['UNRESOLVED', 'OPEN', 'IN_PROGRESS', 'WAITING_HOST', 'RESOLVED', 'CLOSED'],
    columns: [
      column('subject', 'Sujet'),
      column('priority', 'Priorité', 'status'),
      column('status', 'État', 'status'),
      column('created_at', 'Ouvert le', 'date'),
    ],
  },
  reports: {
    title: 'Signalements',
    singular: 'Signalement',
    description: 'Examinez les conversations signalées et consignez les mesures prises.',
    roles: ['owner', 'moderator', 'support'],
    group: 'operations',
    statuses: ['UNRESOLVED', 'REPORTED', 'FROZEN', 'RESOLVED'],
    columns: [
      column('id', 'Conversation'),
      column('status', 'État', 'status'),
      column('updated_at', 'Mise à jour', 'date'),
    ],
  },
  faq_items: {
    title: 'Questions fréquentes',
    singular: 'Question fréquente',
    description: 'Des réponses claires aux questions des utilisateurs.',
    roles: ['owner', 'editor'],
    group: 'content',
    columns: [
      column('question', 'Question'),
      column('category', 'Catégorie'),
      column('publication_status', 'Publication', 'status'),
    ],
    fields: [
      f('question', 'Question', 'text', true),
      f('answer', 'Réponse', 'textarea', true),
      f('category', 'Catégorie'),
    ],
  },
  guides: {
    title: 'Guides locaux',
    singular: 'Guide local',
    description: 'Gérez les informations utiles pour découvrir Gisenyi et ses environs.',
    roles: ['owner', 'editor'],
    group: 'content',
    columns: [
      column('title', 'Guide'),
      column('publication_status', 'Publication', 'status'),
      column('created_at', 'Création', 'date'),
    ],
    fields: [
      f('title', 'Titre', 'text', true),
      f('category_id', 'Identifiant de catégorie'),
      f('summary', 'Résumé', 'textarea'),
      f('content', 'Contenu', 'textarea', true),
      f('image', 'Image (URL HTTPS)', 'url'),
      f('is_new', 'Signaler comme nouveau', 'checkbox'),
    ],
  },
  guide_categories: {
    title: 'Catégories de guides',
    singular: 'Catégorie',
    description: 'Organisez les guides pour faciliter leur découverte.',
    roles: ['owner', 'editor'],
    group: 'content',
    columns: [
      column('title', 'Catégorie'),
      column('description', 'Description'),
      column('publication_status', 'Publication', 'status'),
    ],
    fields: [
      f('title', 'Titre', 'text', true),
      f('description', 'Description', 'textarea'),
      f('icon', 'Nom de l’icône existante'),
    ],
  },
  articles: {
    title: 'Articles',
    singular: 'Article',
    description: 'Préparez et publiez les conseils destinés aux hôtes.',
    roles: ['owner', 'editor'],
    group: 'content',
    columns: [
      column('title', 'Article'),
      column('lang', 'Langue'),
      column('publication_status', 'Publication', 'status'),
    ],
    fields: [
      f('title', 'Titre', 'text', true),
      f('slug', 'Identifiant lisible (slug)', 'text', true),
      f('lang', 'Langue', 'select', true, ['fr', 'en', 'rw', 'sw']),
      f('category', 'Catégorie'),
      f('level', 'Niveau', 'select', false, ['beginner', 'intermediate', 'advanced']),
      f('summary', 'Résumé', 'textarea'),
      f('content', 'Contenu', 'textarea', true),
      f('read_minutes', 'Temps de lecture (minutes)', 'number'),
      f('thumbnail_url', 'Image (URL HTTPS)', 'url'),
      f('has_video', 'Contient une vidéo', 'checkbox'),
      f('video_url', 'Vidéo (URL HTTPS)', 'url'),
    ],
  },
  courses: {
    title: 'Formations',
    singular: 'Formation',
    description: 'Organisez les parcours d’apprentissage des hôtes.',
    roles: ['owner', 'editor'],
    group: 'content',
    columns: [
      column('title', 'Formation'),
      column('level', 'Niveau'),
      column('publication_status', 'Publication', 'status'),
    ],
    fields: [
      f('title', 'Titre', 'text', true),
      f('description', 'Description', 'textarea'),
      f('level', 'Niveau', 'select', false, ['beginner', 'intermediate', 'advanced']),
      f('cover_url', 'Couverture (URL HTTPS)', 'url'),
      f('certificate_badge', 'Libellé du badge'),
    ],
  },
  course_steps: {
    title: 'Étapes de formation',
    singular: 'Étape',
    description: 'Structurez les étapes de chaque formation.',
    roles: ['owner', 'editor'],
    group: 'content',
    columns: [
      column('title', 'Étape'),
      column('type', 'Type'),
      column('position', 'Position'),
      column('publication_status', 'Publication', 'status'),
    ],
    fields: [
      f('course_id', 'Identifiant de formation', 'text', true),
      f('title', 'Titre', 'text', true),
      f('type', 'Type', 'select', true, ['article', 'video', 'quiz']),
      f('duration_minutes', 'Durée (minutes)', 'number'),
      f('position', 'Position', 'number'),
    ],
  },
  legal_documents: {
    title: 'Documents légaux',
    singular: 'Document légal',
    description:
      'Préparez les textes et publiez uniquement les versions approuvées par l’exploitant.',
    roles: ['owner', 'editor'],
    group: 'content',
    columns: [
      column('title', 'Document'),
      column('legal_version', 'Version'),
      column('publication_status', 'Publication', 'status'),
    ],
    fields: [
      f('title', 'Titre', 'text', true),
      f('slug', 'Identifiant lisible (slug)', 'text', true),
      f('legal_version', 'Version du texte', 'text', true),
      f('category', 'Catégorie', 'select', true, [
        'cgu',
        'privacy',
        'cancellation',
        'discrimination',
        'rules',
      ]),
      f('summary', 'Résumé', 'textarea'),
      f('content', 'Texte complet', 'textarea', true),
      f('required', 'Consentement requis', 'checkbox'),
    ],
  },
  errors: {
    title: 'Erreurs applicatives',
    singular: 'Erreur',
    description: 'Consultez les incidents effectivement remontés par l’application.',
    roles: ['owner'],
    group: 'system',
    columns: [
      column('code', 'Erreur'),
      column('route', 'Écran'),
      column('platform', 'Plateforme'),
      column('created_at', 'Date', 'date'),
    ],
  },
  limits: {
    title: 'Limites de requêtes',
    singular: 'Limite',
    description: 'Contrôlez les budgets serveur et leurs fenêtres de mesure.',
    roles: ['owner'],
    group: 'system',
    columns: [
      column('name', 'Limite'),
      column('max_units', 'Unités maximales'),
      column('window_seconds', 'Fenêtre (secondes)'),
    ],
  },
  cleanup: {
    title: 'Nettoyage des fichiers',
    singular: 'Suppression de fichier',
    description: 'Suivez les suppressions R2 planifiées et leurs éventuels échecs.',
    roles: ['owner'],
    group: 'system',
    columns: [
      column('created_at', 'Demandé le', 'date'),
      column('status', 'État', 'status'),
      column('deleted_at', 'Supprimé le', 'date'),
    ],
  },
  audit: {
    title: 'Journal des actions',
    singular: 'Action administrative',
    description: 'Chaque décision et chaque consultation sensible laisse une trace.',
    roles: ['owner'],
    group: 'system',
    columns: [
      column('action', 'Action'),
      column('resource', 'Ressource'),
      column('actor_id', 'Opérateur'),
      column('created_at', 'Date', 'date'),
    ],
  },
  members: {
    title: 'Accès administrateurs',
    singular: 'Accès administrateur',
    description: 'Attribuez à chaque opérateur les droits nécessaires à sa mission.',
    roles: ['owner'],
    group: 'system',
    columns: [
      column('email', 'Opérateur'),
      column('role', 'Rôle'),
      column('active', 'Accès actif'),
      column('created_at', 'Ajouté le', 'date'),
    ],
  },
};
export const allRoles = [...all];
